#!/bin/bash

CUR_DIR=$PWD
SERVERTHREAD_SMALI=$CUR_DIR/services.jar.out/smali/com/android/server/ServerThread.smali

function updateServerThread()
{
    sSmali=$1

    if [ ! -f $sSmali ]; then
        echo "ERROR: $sSmali doesn't exist!"
        echo "       Make sure you are on you device directory!"
        exit 1
    fi
    
    yiServerLine=`grep 'Lcom\/baidu\/service\/YiServiceLoader;->main(Landroid\/content\/Context;)V' $sSmali`
    sed -i '/Lcom\/baidu\/service\/YiServiceLoader;->main(Landroid\/content\/Context;)V/d' $sSmali
    sed -i "/Lcom\/android\/server\/am\/ActivityManagerService;->setWindowManager(Lcom\/android\/server\/wm\/WindowManagerService;)V/a \\\n$yiServerLine" $sSmali

    echo "update $sSmali done"
}

updateServerThread $SERVERTHREAD_SMALI
